package Leetcode;

public class FindtheDifference_389 {

/*
389. Find the Difference - Easy

Description :
    -> You are given two strings s and t.
    -> String t is generated by random shuffling string s and then add one more letter at a random position.
    -> Return the letter that was added to t.


Example 1:
    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.

Example 2:
    Input: s = "", t = "y"
    Output: "y"


Constraints:
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
*/

    static char findTheDifference(String s, String t) {
        int s1 = 0, t1 = 0;
        for (int i = 0; i < t.length(); i++) {
            t1 += (int) t.charAt(i);
        }

        for (int i = 0; i < s.length(); i++) {
            s1 += (int) s.charAt(i);
        }
        return (char) (t1 - s1);
    }

    public static void main(String[] args) {
        System.out.println("389. Find the Difference");

        System.out.println(findTheDifference("xyz", "uxzy"));
    }
}
